# Generated by Django 4.1.2 on 2022-12-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='course_api.coursemodel'),
        ),
    ]
