# Generated by Django 4.1.2 on 2022-10-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_roles_alter_userprofile_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
