# Generated by Django 4.1.2 on 2022-12-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fistname',
            new_name='firstname',
        ),
    ]
