# Generated by Django 4.1.2 on 2022-12-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0001_initial'),
        ('core', '0004_rename_fistname_userprofile_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='course_api.coursemodel'),
        ),
    ]
