# Generated by Django 4.1.2 on 2022-12-11 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('description', models.TextField()),
                ('timecreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CourseModel',
                'verbose_name_plural': 'CourseModels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('description', models.TextField()),
                ('timecreated', models.DateTimeField(auto_now_add=True)),
                ('related_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_api.coursemodel')),
            ],
        ),
    ]
