# Generated by Django 4.1.2 on 2022-12-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0003_coursemodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
    ]
