# Generated by Django 4.1.2 on 2023-01-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0005_alter_coursemodel_author_alter_coursemodel_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='key',
            field=models.CharField(default='164uy5', max_length=6, unique=True),
        ),
    ]
