# Generated by Django 4.1.2 on 2023-01-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0006_coursemodel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='key',
            field=models.CharField(default='s8qfuv', editable=False, max_length=6, unique=True),
        ),
    ]
