# Generated by Django 4.1.2 on 2023-01-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0009_alter_coursemodel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='key',
            field=models.CharField(default='rdlst4', editable=False, max_length=6, unique=True),
        ),
    ]
