# Generated by Django 4.1.2 on 2023-01-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0010_alter_coursemodel_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='access',
            field=models.CharField(default=1, max_length=10, verbose_name=((0, 'Public'), (1, 'Private'))),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='key',
            field=models.CharField(default='xgippm', editable=False, max_length=6),
        ),
    ]
